### ISSUE TITLE
dotnet3.1 installed but still can't find on linux 

### ISSUE THREAD

**Issue by StarGazerM** [FunctionalCorrectness/VS-Code-Language-Server-for-Dafny#72]
Hi:
    I am using manjaro linux and install this plugin but when I open a .dfy file, error pops
> There is no compatible dotnet runtime installed. Dafny requires the ASP.NET Core Runtime 3.1.

   my dotnet runtime installation looks like this and I can build dafny from source
```
$  dotnet --list-runtimes
Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by camrein** [comment]
Please note that the repository of the latest version is now https://github.com/DafnyVSCode/ide-vscode
To answer your question: Although you have a .NET Core 3.1 runtime installed, it is not the required ASP.NET Core runtime as the error states. The plugin searches for an entry like the following:
```sh
Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
```

As I don't know manjaro linux, I'll give you a short example for ubuntu:
```sh
sudo apt-get install aspnetcore-runtime-3.1
```

Otherwise consult the Microsoft documentation: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#install-the-runtime

**Comment by StarGazerM** [comment]
ah thanks, successfully installed!
